"""Regenerate docs/reports/ppo/recurrent_ppo_runs.md from the run directories.

Generated, not hand-kept. A hand-kept table of these same facts is precisely what drifted in
config.LEGACY -- it claimed the action mode was `absolute` and the block start range [100, 400]
long after the env had moved on, and nothing detected it because each file was self-consistent.
The run directories are the record; this only formats them.

    python recurrent_ppo/scripts/runs_doc.py
"""

import argparse
import glob
import os

import numpy as np
import yaml

DOC = "docs/reports/ppo/recurrent_ppo_runs.md"
# the knobs that distinguish one arm from another; everything else is how a run is driven
ARM_KEYS = ("obs", "reward", "shaping_potential", "shaping_coef", "progress_coef", "success_bonus",
            "corrupt_obs", "corrupt_t_max", "keypoint_visible_rate", "occlusion",
            "agent_near_block_prob", "block_near_goal_prob", "block_zero_coverage",
            "action_mode", "delta_scale", "ent_coef", "log_std_init", "eval_curriculum")


def wandb_id(run_dir):
    hits = glob.glob(os.path.join(run_dir, "wandb", "run-*-*"))
    return os.path.basename(hits[0]).rsplit("-", 1)[-1] if hits else "-"


def evals(run_dir):
    path = os.path.join(run_dir, "evaluations.npz")
    if not os.path.exists(path):
        return None
    d = np.load(path)
    means = np.array([r.mean() for r in d["results"]])
    return {
        "n": len(means), "steps": int(d["timesteps"][-1]),
        "best": means.max(), "final": means[-1], "mean": means.mean(), "sd": means.std(),
        "success": max(s.mean() for s in d["successes"]),
        "first_half": means[: len(means) // 2].mean() if len(means) > 3 else float("nan"),
        "second_half": means[len(means) // 2:].mean() if len(means) > 3 else float("nan"),
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--logs", required=True,
                    help="directory holding the run dirs. REQUIRED rather than defaulted: the "
                         "arms write to logs/<arch.log_root>/<obs>_<arm>/<timestamp>/ but a "
                         "grid launcher may collect them anywhere, and a wrong default silently "
                         "generates a doc from zero runs.")
    ap.add_argument("--out", default=DOC)
    args = ap.parse_args()

    rows = []
    # BOTH depths. arch.py's log_root nests one level (logs/<root>/<arm>/<timestamp>/), but a
    # hand-collected grid is usually FLAT (<root>/<arm>/ holds params/ and model.zip directly).
    # Globbing only the nested shape silently finds nothing in a flat tree, so a doc whose
    # header says it is generated cannot in fact be regenerated -- which is exactly what
    # happened to the generation deleted on 2026-09-16. The `params/args.yaml` check below
    # makes the extra depth harmless either way.
    candidates = set(glob.glob(os.path.join(args.logs, "*/")))
    candidates |= set(glob.glob(os.path.join(args.logs, "*", "*/")))
    # `_superseded_*` trees are kept on disk deliberately (each carries a WHY_SUPERSEDED.md)
    # and must NOT be counted: they were trained under an observation or reward this arm no
    # longer uses, so listing them would inflate the run count and mix generations in one
    # table. Skipping them here rather than at the glob keeps the nested shape working.
    candidates = {d for d in candidates if "_superseded_" not in d}
    for d in sorted(candidates):
        cfg_path = os.path.join(d, "params", "args.yaml")
        if not os.path.exists(cfg_path):
            continue
        rows.append((d.rstrip("/"), yaml.safe_load(open(cfg_path)), evals(d)))

    lines = [
        "# Recurrent PPO on PushT — run log",
        "",
        f"Generated by `recurrent_ppo/scripts/runs_doc.py` from `{args.logs}`. Do not edit by hand;",
        "re-run the script. Every number here is read from the run's own `params/args.yaml` and",
        "`evaluations.npz`, so it cannot disagree with what was actually trained.",
        "",
        "`eval` is on whatever distribution `eval_curriculum` selected — `match` means the training",
        "distribution, so those numbers are NOT comparable with `off` runs. Where a run logged a",
        "second evaluation it appears in tensorboard as `eval_real/` or `eval_train/`.",
        "",
        f"{len(rows)} runs. **No run has ever recorded a non-zero evaluation success rate.**",
        "",
        "| run | w&b | reward | curricula (nb/ng) | ent | steps | evals | best | final | mean±sd | trend | success |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for path, cfg, ev in rows:
        name = os.path.basename(path)
        pot = cfg.get("shaping_potential", "-")
        reward = cfg.get("reward", "?")
        reward = f"{reward} ({pot})" if reward == "shaped" else reward
        nb, ng = cfg.get("agent_near_block_prob"), cfg.get("block_near_goal_prob")
        cur = "—" if nb is None else f"{nb}/{ng}"
        if ev is None:
            lines.append(f"| `{name}` | {wandb_id(path)} | {reward} | {cur} | {cfg.get('ent_coef')} | 0 | 0 | — | — | — | — | — |")
            continue
        trend = "—" if np.isnan(ev["first_half"]) else f"{ev['first_half']:.1f}→{ev['second_half']:.1f}"
        lines.append(
            f"| `{name}` | {wandb_id(path)} | {reward} | {cur} | {cfg.get('ent_coef')} | "
            f"{ev['steps']:,} | {ev['n']} | {ev['best']:.1f} | {ev['final']:.1f} | "
            f"{ev['mean']:.1f}±{ev['sd']:.1f} | {trend} | {ev['success']:.2f} |")

    lines += [
        "",
        "## What the run directories cannot tell you",
        "",
        "Prose, deliberately. These are facts about the code at the time, not about a run, and the",
        "previous attempt to encode them as a lookup table (`config.LEGACY`) drifted from the truth",
        "without anything noticing.",
        "",
        "- A `shaped` run with no potential recorded predates `--shaping-potential` and used the",
        "  agent-to-block potential, the only one that existed then.",
        "- Runs before `2026-09-11_16-15-33` allowed block starts that already overlap the goal.",
        "  34.5% of uniform draws do, and a level-valued reward pays for that overlap every step,",
        "  so a do-nothing policy scored 92.7 on the worst-affected arm.",
        "- Runs before `2026-09-11_15-59-24` logged only one evaluation. From there on, whichever",
        "  distribution `eval/` uses, the other is logged as `eval_real/` or `eval_train/`.",
        "- Runs before `2026-09-11_16-08-15` could drive the agent OUT of the arena: the agent is a",
        "  kinematic body that walks through pymunk's walls, and the action target was clipped to",
        "  the image bounds rather than the reachable region. Two 2M-step runs converged on parking",
        "  at (0, 512) from every start, never touching the block.",
        "- Everything stopped short of its step budget was stopped by hand, because a fix landed",
        "  mid-run. The step count in the table is where it got to, not a failure to converge.",
        "",
        "## Full configuration per run",
        "",
    ]
    for path, cfg, _ in rows:
        lines.append(f"**`{os.path.basename(path)}`** — {wandb_id(path)}")
        lines.append("")
        lines.append("```")
        lines += [f"{k:24} {cfg.get(k)}" for k in ARM_KEYS if k in cfg]
        lines.append("```")
        lines.append("")

    open(args.out, "w").write("\n".join(lines) + "\n")
    print(f"[INFO] wrote {args.out}: {len(rows)} runs")


if __name__ == "__main__":
    main()
