"""Regenerate docs/reports/archive/ARM_RANKING_BY_BLOCKMOTION.md from analysis/arm_ranking/step_*.json.

    python scripts/build_blockmotion_doc.py [-o docs/reports/archive/ARM_RANKING_BY_BLOCKMOTION.md]

Organised by SUBSET first, because the two subsets are different measurements and pooling
them would hide the only thing that makes the still-block tables readable: most of that pool
is tied. Within a subset, one table per quantity so arms can be read down a column.

EVERY EVALUATED STEP APPEARS and none is marked best -- selection is never done on test.
"""
import argparse
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / 'analysis' / 'arm_ranking'
STEPS = [10000, 50000, 100000]
SUBSETS = [('block_moving', "the demo's chunk MOVES the block"),
           ('block_still', "the demo's chunk does NOT move the block")]


def load():
    out = {}
    for f in sorted(SRC.glob('step_*.json')):
        try:
            d = json.loads(f.read_text())
            out[int(d['step'])] = d
        except (ValueError, KeyError, json.JSONDecodeError):
            continue
    return out


def table(rows, sub, labels, head, get, fmt='{:.1%}'):
    L = [f'\n**{head}**\n', f'| source | {" | ".join(f"{s//1000}k" for s in STEPS)} |',
         f'|---|{"--:|" * len(STEPS)}']
    for lab in labels:
        cells = []
        for s in STEPS:
            d = rows.get(s)
            v = None
            if d and sub in d['subsets']:
                v = get(d['subsets'][sub]['by_source'].get(lab, {}))
            cells.append('—' if v is None else fmt.format(v))
        L.append(f'| {lab} | {" | ".join(cells)} |')
    return '\n'.join(L) + '\n'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('-o', '--out', default=str(ROOT / 'docs/reports/archive/ARM_RANKING_BY_BLOCKMOTION.md'))
    args = ap.parse_args()
    rows = load()
    if not rows:
        print(f'nothing under {SRC}'); return
    any_d = rows[sorted(rows)[0]]
    labels, P, n_arm = any_d['arm_labels'], any_d['pool_size'], any_d['n_per_arm']
    chance_arm, chance_star = n_arm / P, 1 / P

    A = [f"""# Every arm's predictions in one verifier ranking, split by whether the block moves

Generated by `scripts/build_blockmotion_doc.py` from `scripts/rank_arms_by_blockmotion.py`
output. Do not hand-edit.

At each held-out decision state, five arms each propose **{n_arm}** candidates. Those go into a
single pool with **{n_arm}** block-directed uniform samples and the demonstrator's own action
a\\*, and **one shared verifier** (`t_goal`) scores all **{P}**. The pool is then ranked twice:

| ranking | direction | what it measures |
|---|---|---|
| **verifier value** | higher better | what best-of-n actually selects on |
| **RMSE to a\\*** | lower better | how close the prediction is to the demonstrator |

Both are taken over the executed window `action[To-1 : To-1+Ta]`, the same 8 waypoints the
verifier simulates. a\\* is excluded from the RMSE ranking — its RMSE to itself is 0, so it
would win every decision by construction — but kept in the verifier ranking, where its
position is a real measurement.

**Chance shares.** An arm owns {n_arm} of {P} columns, so **{chance_arm:.1%}** is chance;
a\\* owns one column, so its chance is **{chance_star:.1%}**. Mean verifier rank is out of {P}
(chance {(P-1)/2:.1f}); the RMSE rank excludes a\\* so it is out of {P-1} (chance {(P-2)/2:.1f}).

**Ties get fractional credit.** Every decision contributes exactly 1.0 to the top-1 tally
however degenerate its values are, so a fully tied decision spreads {chance_star:.1%} to each
column rather than handing the win to whichever index sorts first.

**The two subsets are different measurements.** `expert_moved` asks whether the
demonstrator's own block pose changes over this chunk — a property of the state, so the same
decisions fall in each subset for every arm and the comparison is paired.
""", f"""
| subset | decisions | pooled-blind @10k → 100k |
|---|--:|--:|
"""]
    for sub, _ in SUBSETS:
        ns = [rows[s]['subsets'][sub] for s in STEPS if s in rows and sub in rows[s]['subsets']]
        if ns:
            A.append(f"| `{sub}` | {ns[0]['n_decisions']} | "
                     f"{ns[0]['p_blind']:.1%} → {ns[-1]['p_blind']:.1%} |\n")
    A.append(f"""
*pooled-blind* = no candidate from **any** of the five arms moves the T, so the verifier
ranks nothing. This is stricter than the per-arm blind rate in `docs/reports/archive/ASTAR_RECALL.md` and comes out
far lower — five policies rarely all miss the block at once. The two answer different
questions; do not compare them.
""")

    for sub, desc in SUBSETS:
        A.append(f'\n## {sub} — {desc}\n')
        A.append(table(rows, sub, labels, f'Share of verifier top-1 (chance {chance_arm:.1%}, '
                       f'a\\* {chance_star:.1%})', lambda b: b.get('verifier_top1_share')))
        A.append(table(rows, sub, labels, 'Share of RMSE top-1 — who is closest to a\\*',
                       lambda b: b.get('rmse_top1_share')))
        A.append(table(rows, sub, labels, f'Mean verifier rank of {P} (chance {(P-1)/2:.1f}; lower is better)',
                       lambda b: b.get('verifier_mean_rank'), '{:.1f}'))
        A.append(table(rows, sub, labels,
                       'Closest candidate to a\\*, mean euclidean px (lower is better)',
                       lambda b: b.get('euclid_best_px'), '{:.1f}'))
        # final(n) vs best(n): the readout that separates conditioning from the running max
        NS = [1, 2, 4, 8, 16]
        for key, title, fmt in [
                ('final_value', 'final(n) — verifier value of slot n-1, the most-conditioned '
                                'draw, executed WITHOUT consulting the verifier', '{:.2f}'),
                ('best_value', 'best(n) — verifier value of the max over slots 0..n-1, what '
                               'argmax executes', '{:.2f}'),
                ('final_euclid_px', 'final(n) — euclidean distance to a\\* (px)', '{:.1f}'),
                ('best_euclid_px', 'best(n) — closest of the first n to a\\* (px)', '{:.1f}')]:
            L = [f'\n**{title}**\n',
                 f'| source | step | {" | ".join(f"n={n}" for n in NS)} | Δ n=1→16 |',
                 f'|---|--:|{"--:|" * (len(NS) + 1)}']
            for lab in labels:
                for st in STEPS:
                    d = rows.get(st)
                    b = (d['subsets'][sub]['by_slot'].get(lab)
                         if d and sub in d['subsets'] and 'by_slot' in d['subsets'][sub] else None)
                    if not b:
                        continue
                    v = b[key]
                    cells = ' | '.join(fmt.format(v[n - 1]) for n in NS)
                    L.append(f'| {lab} | {st//1000}k | {cells} | {v[-1] - v[0]:+.2f} |')
            A.append('\n'.join(L) + '\n')
        A.append("""
`best(n)` rises with n for **any** source, i.i.d. noise included — it is a running maximum
over more draws. `final(n)` rises only if the scored context actually steers generation. BC
and ST k=1 consume no context, so their `final(n)` is the control and must be flat.

**The `uniform` row is not a clean per-slot null.** `uniform_chunks` tiles the 8 kept wedges
twice, so slot k and slot k+8 share a direction and the slots differ systematically by
geometry rather than being exchangeable. Its `final(n)` movement is therefore an artefact of
that tiling and serves as a noise floor: an arm whose `final(n)` gain does not exceed
uniform's is not steering. Every other table in this file aggregates over all 16 uniform
columns and is unaffected.
""")

        L = ['\n**Do the two rankings agree?**\n',
             f'| | {" | ".join(f"{s//1000}k" for s in STEPS)} |', f'|---|{"--:|" * len(STEPS)}']
        for name, key, fmt in [
                ('Spearman(verifier, −RMSE)', 'spearman_verifier_vs_rmse', '{:+.3f}'),
                ('verifier top-1 is also RMSE top-1', 'top1_overlap', '{:.1%}'),
                (f'RMSE-best sits at verifier rank (chance {(P-2)/2:.1f})',
                 'rmse_best_mean_verifier_rank', '{:.1f}')]:
            cells = []
            for s in STEPS:
                d = rows.get(s)
                v = d['subsets'][sub]['agreement'].get(key) if d and sub in d['subsets'] else None
                cells.append('—' if v is None else fmt.format(v))
            L.append(f'| {name} | {" | ".join(cells)} |')
        A.append('\n'.join(L) + '\n')

    A.append(f"""
## Reading these

The uniform sampler is **block-directed by construction** — its radius is drawn up to the
95th percentile of the expert's own net move and its direction into the half-plane facing the
block. So it is a goal-directed random baseline, not arbitrary noise, and a policy losing to
it means the policy adds nothing over "push roughly toward the block". Its `euclid best` is
constant across steps because it does not train; that makes it a fixed yardstick the arms can
be watched crossing.

One seed, one dataset (`split-blq`, 137 demos), test split held out **by geometry**, so every
number is an out-of-region readout and none of it is comparable to `docs/reports/SUCCESS_RATES.md`.
""")
    pathlib.Path(args.out).write_text(''.join(A))
    print(f'wrote {args.out}  ({len(rows)} steps)')


if __name__ == '__main__':
    main()
