"""Regenerate ASTAR_RECALL.md from the on-disk astar_uniform_walk output.

    python scripts/build_astar_doc.py [-o ASTAR_RECALL.md]

Organised by QUESTION rather than by arm, because the questions are not independent: how
often the verifier can distinguish anything at all bounds what every later table is allowed
to mean. Read them in order.

EVERY EVALUATED CHECKPOINT APPEARS and none is marked best -- selection is never done on
test. A missing cell is a (arm, step) not yet on disk, which during a live sweep is normal.
"""
import argparse
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / 'analysis' / 'astar_recall'
STEPS = [10000, 50000, 100000]
# canonical-dir substring -> (label, order). The UNet BC stem is not `value_k*`, so
# analysis_run_name.canonical() passes it through and its directory is the raw run name.
ARMS = [('unetbc_ver-t_goal', 'BC (UNet)'),
        ('son-none_value_k1_', 'ST k=1'),
        ('son-none_value_k16_', 'ST k=16 (uniform)'),
        ('son-flat400_value_k16_', 'ST k=16 + flat t=400'),
        ('son-ramp400to200_value_k16_', 'ST k=16 + ramp 400->200')]


def load():
    """{(arm_label, step): payload} for everything on disk."""
    out = {}
    if not SRC.is_dir():
        return out
    for d in sorted(SRC.iterdir()):
        if not d.is_dir():
            continue
        label = next((lab for key, lab in ARMS if key in d.name), None)
        if label is None:
            continue
        for f in sorted(d.glob('step_*.json')):
            try:
                out[(label, int(f.stem.split('_')[1]))] = json.loads(f.read_text())
            except (ValueError, IndexError, json.JSONDecodeError):
                continue
    return out


def table(rows, head, get, fmt='{:.2f}'):
    """One `arm x step` block. `get` returns a number or None for a cell."""
    L = [f'| arm | {" | ".join(f"{s//1000}k" for s in STEPS)} |',
         f'|---|{"--:|" * len(STEPS)}']
    for _, lab in ARMS:
        cells = []
        for s in STEPS:
            p = rows.get((lab, s))
            v = None if p is None else get(p)
            cells.append('—' if v is None else (fmt.format(v) if not isinstance(v, str) else v))
        L.append(f'| {lab} | {" | ".join(cells)} |')
    return f'\n### {head}\n\n' + '\n'.join(L) + '\n'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('-o', '--out', default=str(ROOT / 'ASTAR_RECALL.md'))
    args = ap.parse_args()
    rows = load()
    if not rows:
        print(f'nothing under {SRC}'); return

    any_p = next(iter(rows.values()))
    n = any_p['n']
    done = sorted({k[1] for k in rows})
    A = [f"""# Is a* generated, and does the verifier rank it best?

Generated by `scripts/build_astar_doc.py` from the on-disk output of
`scripts/astar_uniform_walk.py`. Do not hand-edit.

Five arms on `split-blq` / 137 demos / seed 42 / `ver-t_goal` / `enc-resnet18`, read
OPEN-LOOP along each test episode's own demo states -- the only states where the expert
action a* exists at all. Once a rollout diverges there is no a* for the state it is in, so
a per-state comparison there would be a claim about a different state.

At every decision the verifier scores three things through the SAME `_score_candidates`
call: the policy's {n} candidates, {n} hand-built uniform samples that owe nothing to the
policy, and a* itself. Budgets are matched at {n} v {n}, so the provenance null is a coin flip.

Steps on disk: {', '.join(f'{s//1000}k' for s in done)}. Cells are `—` where not yet written.

## 1. When can the verifier tell anything apart?

Under `t_goal` the value is a function of where the T ends up, so every candidate that never
contacts the block returns the IDENTICAL score. A decision where NO candidate moves the T is
**blind**: the verifier expresses no preference, argmax is an arbitrary tie-break toward
index 0, and best-of-n buys nothing there. This bounds every table below -- `n` is a real
test-time-compute axis only on the non-blind fraction.
"""]
    A.append(table(rows, 'Blind decisions (policy candidates) — fraction',
                   lambda p: p['informativeness']['policy']['p_blind'], '{:.1%}'))
    A.append(table(rows, f'Effective search width — distinct verifier values out of {n}',
                   lambda p: p['informativeness']['policy']['mean_distinct']))
    A.append(table(rows, 'Blind fraction during the APPROACH phase (before the demo first moves the T)',
                   lambda p: (p['informativeness']['policy']['by_phase'].get('approach') or {}).get('p_blind'),
                   '{:.1%}'))
    A.append("""
## 2. Whose action does the verifier prefer?

`uniform beats policy` is the head-to-head: how often the best of {n} blind uniform samples
outscores the best of the policy's own {n} candidates. The null is 50%. Well above it means
best-of-n is limited by what the policy GENERATES, not by the ranking.

**Read this against the reach table.** The uniform competitor draws its radius up to a cap
set at the 95th percentile of the expert's own net move, so if the policy's chunks are much
shorter, part of any uniform win is reach rather than aim.
""".replace('{n}', str(n)))
    A.append(table(rows, 'Uniform beats policy, head-to-head',
                   lambda p: p['provenance']['uniform_beats_policy'], '{:.1%}'))
    A.append(table(rows, "Verifier's top pick came from the policy",
                   lambda p: p['provenance']['p_policy'], '{:.1%}'))
    A.append(table(rows, 'Reach audit — median net move of a policy candidate (px)',
                   lambda p: p['reach']['policy_net_move_px_p5_50_95'][1], '{:.1f}'))
    A.append(table(rows, 'Reach audit — median net move of a* (px)',
                   lambda p: p['reach']['astar_net_move_px_p5_50_95'][1], '{:.1f}'))
    A.append(f"""
## 3. Is a* sampled?

`nearest draw` is the distance from the CLOSEST of the {n} candidates to a*'s endpoint. On
its own that is unreadable -- a wide cloud lands near a* by luck -- so `ratio` divides it by
the cloud's own spread at that decision. **ratio < 1** means the draws reach a* more closely
than they reach each other, i.e. a* is inside the support rather than merely near a big blob.
""")
    A.append(table(rows, 'Nearest of the n draws to a* (px)',
                   lambda p: p['recall']['min_endpoint_dist_px'], '{:.1f}'))
    A.append(table(rows, 'Ratio: nearest-draw distance / cloud spread  (<1 = a* inside the support)',
                   lambda p: p['recall']['min_dist_over_spread']))
    A.append(table(rows, 'Decisions where a* falls within the candidate spread',
                   lambda p: p['recall']['frac_decisions_a_star_inside_spread'], '{:.0%}'))
    A.append(f"""
## 4. Does the verifier rank a* above the candidates?

Mean rank of a* among the {n} candidates, **on informative decisions only**. Ties count as
half, so a decision where a* ties everything scores {n/2:.0f} -- chance -- instead of the
worst-possible {n}. Under the null that a* is exchangeable with the candidates: rank
{n/2:.1f}, fraction beaten 0.500.

Below {n/2:.1f} means the verifier ranks the expert action BETTER than a typical candidate.
""")
    A.append(table(rows, f'Mean rank of a* out of {n} (informative decisions; chance = {n/2:.1f})',
                   lambda p: (p['astar'].get('informative') or {}).get('mean_rank', {}).get('v')))
    A.append(table(rows, 'Fraction of candidates a* beats (informative; chance = 0.500)',
                   lambda p: (p['astar'].get('informative') or {}).get('frac_candidates_beaten', {}).get('v'),
                   '{:.3f}'))
    A.append("""
## 5. Does the ranking steer toward a*?

Spearman correlation, across the n candidates of one decision, between the verifier score and
MINUS the distance to a*. Positive means the verifier prefers candidates nearer the expert, so
the scored context handed to the next candidate points that way. **~0 means the ordering is
orthogonal to the expert** -- whatever the search context is conditioning on, it is not
"closer to what the demonstrator did".

`slot 0 -> slot n-1` is the mean distance to a* at each slot index. For ST k=1 and BC the
slots are i.i.d. draws with no context, so those two rows MUST be flat; a trend there would
be a bug in the slot bookkeeping, not a result.
""")
    A.append(table(rows, 'Spearman(verifier score, -distance to a*), informative decisions',
                   lambda p: p['steering'].get('spearman_informative_only',
                                               p['steering']['spearman_score_vs_astar']),
                   '{:+.3f}'))

    def slot_trend(p):
        b = (p['steering'].get('dist_to_astar_by_slot_px_informative')
             or p['steering']['dist_to_astar_by_slot_px'])
        return f'{b[0]:.0f} → {b[-1]:.0f}'
    A.append(table(rows, 'Distance to a* by slot, px (slot 0 → slot n-1)', slot_trend))

    A.append(f"""
## Provenance of these numbers

Every cell comes from one `scripts/astar_uniform_walk.py` run, `--split test`, n={n},
all decisions of the walked episodes at a stride of `n_action_steps`. Per-run JSON lives
under `analysis/astar_recall/<canonical name>/step_<7-digit>.json` and carries the full
stratification, the bootstrap CIs, and the per-phase breakdown that these summary tables
flatten.
""")
    pathlib.Path(args.out).write_text(''.join(A))
    print(f'wrote {args.out}  ({len(rows)} run-steps)')


if __name__ == '__main__':
    main()
