"""Regenerate docs/reports/archive/SUCCESS_RATES_GEOMETRIC.md from the on-disk eval output.

The geometric-split sweep: 3 arms x 5 datasets whose TEST split is held out BY GEOMETRY --
a quadrant of T start poses, or the arena interior against a band along the walls (the
manifests are README_pusht.md 2.2, generated by scripts/make_geometric_splits.py). So every
number here is an OUT-OF-REGION readout, not a same-distribution one, and it is not
comparable to any row of docs/reports/SUCCESS_RATES.md.

Organised by DATASET, because that is the axis the experiment varies. Within a dataset the
three arms sit in one table so they can be read against each other at matched n.

EVERY EVALUATED CHECKPOINT APPEARS, and no step is marked as best -- selection is never done
on test. A missing cell means that (run, rule, step, n) is not on disk yet, which during a
live sweep is the normal state.

    python scripts/build_geometric_splits_doc.py [-o docs/reports/archive/SUCCESS_RATES_GEOMETRIC.md]
"""
import argparse
import json
import os
import pathlib

ROOT = pathlib.Path(os.environ.get(
    'DP_OUTPUT_ROOT', '/gscratch/robotics/harine/diffusion_policy_outputs'))
TASK = ROOT / 'pusht_search' / 'pusht_image_search_imgonly'
SPLITS = pathlib.Path(__file__).resolve().parents[1] / 'diffusion_policy/config/splits'
NS = [1, 2, 4, 8, 16, 32, 64]
ENC = os.environ.get('ENC_TAG', 'enc-resnet18')

# (section, label, split_suffix, n_demos, manifest) -- mirrors scripts/run_geometric_splits.sh.
DATASETS = [
    ('Quadrant held out', 'eval = bottom-left quadrant', '_split-blq', 137,
     'pusht_blockquad_bottomleft_train137.json'),
    ('Quadrant held out', 'eval = top-right quadrant', '_split-trq', 173,
     'pusht_blockquad_topright_train173.json'),
    ('Border band', 'train = 30 nearest-wall, eval = interior core', '_split-brd30', 30,
     'pusht_blockborder_train30_core50.json'),
    ('Border band', 'train = 60 nearest-wall, eval = interior core', '_split-brd60', 60,
     'pusht_blockborder_train60_core50.json'),
    ('Border band', 'train = 100 nearest-wall, eval = interior core', '_split-brd100', 100,
     'pusht_blockborder_train100_core50.json'),
]
# trainer subdir | run-name stem | doc label
ARMS = [('unet_bc', 'unetbc_ver-t_goal', 'BC (UNet)'),
        ('offline', 'value_k1_ver-t_goal', 'ST k=1'),
        ('outer_inner', 'value_k16_ver-t_goal', 'ST k=16 (uniform)')]
RULES = [('argmax', 'argmax'), ('final_pass', 'final candidate')]

# The OBS-NOISE arms (README_pusht.md 2.4). All ST k=16, on a subset of the datasets, with
# an extra suffix between ver-t_goal and enc-. Parts 1/2 register a slot ladder so they also
# carry the `_obs-corrupt` readout; part 3's corruption is image-space and train-only, so it
# has no eval-time condition to reproduce and takes the clean rows only.
NOISE_ARMS = [
    ('_son-flat800', 'flat t=800', True),
    ('_son-flat400', 'flat t=400', True),
    ('_son-flat200', 'flat t=200', True),
    ('_son-ramp800to400', 'ramp 800->400', True),
    ('_son-ramp400to200', 'ramp 400->200', True),
    ('_gm-t800-T3px', 'goal mask t=800, T+3px', False),
]
NOISE_TAGS = {'_split-blq': 137, '_split-brd60': 60}


def noise_rows(infix, demos, tag, sel, obs):
    """{step: {n: value}} for one obs-noise arm, test split."""
    f = (TASK / 'outer_inner'
         / f'value_k16_ver-t_goal{infix}_{ENC}_demos-{demos}{tag}_seed-42'
         / f'bon_search_sel-{sel}_obs-{obs}' / 'success_curves.jsonl')
    if not f.is_file():
        return {}
    out = {}
    for line in f.read_text().splitlines():
        if not line.strip():
            continue
        d = json.loads(line)
        cur = out.setdefault(int(d['step']), {})
        for n, sr in zip(d.get('n') or [], d.get('success_rate') or []):
            if sr is not None:
                cur[int(n)] = float(sr)
    return out


def rows(sub, stem, demos, tag, sel):
    """{step: {n: value}} for one (arm, dataset, selection rule), test split.

    Later rows win on a repeated step: eval_search_pusht merges by n into the same file, so
    a resubmitted watcher appends rather than rewrites and the last row is the current one.
    """
    f = (TASK / sub / f'{stem}_{ENC}_demos-{demos}{tag}_seed-42'
         / f'bon_search_sel-{sel}_obs-clean' / 'success_curves.jsonl')
    if not f.is_file():
        return {}, f
    out = {}
    for line in f.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        d = json.loads(line)
        cur = out.setdefault(int(d['step']), {})
        for n, sr in zip(d.get('n') or [], d.get('success_rate') or []):
            if sr is not None:
                cur[int(n)] = float(sr)
    return out, f


def table(label, per_arm):
    """One markdown table: rows are (arm, step), columns are n."""
    head = f'| arm | step | ' + ' | '.join(f'n={n}' for n in NS) + ' |'
    rule = '|---|--:|' + '--:|' * len(NS)
    body = []
    for arm_label, steps in per_arm:
        if not steps:
            body.append(f'| {arm_label} | — | ' + ' | '.join('—' for _ in NS) + ' |')
            continue
        for i, step in enumerate(sorted(steps)):
            cells = [f'{steps[step][n]:.2f}' if n in steps[step] else '—' for n in NS]
            body.append(f'| {arm_label if i == 0 else ""} | {step//1000}k | '
                        + ' | '.join(cells) + ' |')
    return '\n'.join([f'**{label}** — test success rate', '', head, rule] + body)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('-o', '--out', default='docs/reports/archive/SUCCESS_RATES_GEOMETRIC.md')
    args = ap.parse_args()

    L = ['# PushT success rates — geometric splits',
         '',
         'Generated by `scripts/build_geometric_splits_doc.py` from the on-disk eval output.',
         'Do not hand-edit.',
         '',
         'Three arms — **BC (UNet)**, **ST k=1**, **ST k=16 with uniform slot weights** —',
         'trained on each of the five geometric split manifests (README_pusht.md §2.2), and',
         'evaluated on each manifest\'s own held-out TEST episodes.',
         '',
         '**These numbers are not comparable to `docs/reports/SUCCESS_RATES.md`.** There the test split is a',
         'random draw from the same distribution as train; here it is a *region of T start poses*',
         'the policy never trained on, so a lower number is expected and the interesting quantity',
         'is the gap between arms, not the level.',
         '',
         f'Encoder: `{ENC}` — ResNet18 trained end to end, the default restored on 2026-08-30',
         '(`pusht_base.yaml:66`). Not the frozen SD-VAE generation. Verifier value: `t_goal`.',
         'Seed 42, one seed. Rollouts: 50 environments, `--skip-val`.',
         '',
         'Two readout rules on the same weights: **argmax** executes the candidate the verifier',
         'ranks first; **final candidate** (`final_pass`) executes the last one generated and',
         'never consults the verifier for selection. At n=1 they are the same measurement.',
         '',
         'Every evaluated checkpoint is listed and none is marked best — selection is never done',
         'on test. `—` means that cell is not on disk yet.',
         '']

    section = None
    for sec, label, tag, demos, manifest in DATASETS:
        if sec != section:
            L += [f'## {sec}', '']
            section = sec
        m = json.loads((SPLITS / manifest).read_text())
        L += [f'### {label}', '',
              f'`{manifest}` — train {len(m["train"])} / val {len(m["val"])} / '
              f'test {len(m["test"])} episodes.', '']
        for sel, sel_label in RULES:
            per_arm, missing = [], 0
            for sub, stem, arm_label in ARMS:
                r, _ = rows(sub, stem, demos, tag, sel)
                per_arm.append((arm_label, r))
                missing += (not r)
            L += [table(f'selection: {sel_label}', per_arm), '']
            if missing:
                L += [f'*{missing} of {len(ARMS)} arms have no `sel-{sel}` output yet.*', '']

    # ---- obs-noise arms -------------------------------------------------------------
    L += ['## Observation-noise arms (ST k=16)', '',
          'All ST k=16 with uniform slot weights, on `blq` and `brd60` only. Three mechanisms:',
          '',
          '- **flat** — every one of the 16 candidate slots pinned at the same timestep',
          '  (`slot_obs_noise.mode=list`). Deliberately not a ladder: the control the graded',
          '  arms are read against.',
          '- **ramp** — slot 0 at the base timestep, slot 15 at HALF THAT TIMESTEP, linear in',
          '  t. Not half the corruption: `alpha_bar` is a cumulative product, so t 800→400',
          '  moves √ᾱ 0.039 → 0.440.',
          '- **goal mask** — noise on the observation IMAGE inside a mask around the goal T',
          '  (T dilated 3 image px = 5.8% of the frame), before the encoder. A different',
          '  mechanism from the slot ladder, and **train-split only** — val, test and the env',
          '  runner are clean — so it is not comparable to the flat/ramp rows.',
          '',
          'Levels transfer from the SD-VAE calibration unchanged: `_corrupt_obs_features`',
          'scales the noise by a running per-dimension feature std, so t fixes an SNR, not a',
          'magnitude. Measured mean-centred cosine at t=800/400/200 is 0.041/0.448/0.792 for',
          'ResNet18 against 0.003/0.426/0.810 for the VAE.',
          '',
          '`obs-corrupt` reproduces the slot→level mapping the loss trained under;',
          '`obs-clean` evaluates every slot clean. The goal-mask arm has no ladder, so the',
          'corrupt flag is a no-op on it and only clean rows exist.',
          '']
    for tag, demos in NOISE_TAGS.items():
        L += [f'### dataset `{tag.lstrip("_")}` (train {demos})', '']
        for sel, sel_label in RULES:
            for obs in ('clean', 'corrupt'):
                per_arm = []
                for infix, arm_label, has_ladder in NOISE_ARMS:
                    if obs == 'corrupt' and not has_ladder:
                        continue
                    per_arm.append((arm_label, noise_rows(infix, demos, tag, sel, obs)))
                if not per_arm or not any(r for _, r in per_arm):
                    continue
                L += [table(f'selection: {sel_label} — obs {obs}', per_arm), '']

    L += ['---', '',
          '## Reproducing',
          '',
          '```bash',
          'python scripts/make_geometric_splits.py                    # the five manifests',
          'SUBMIT=1 bash scripts/run_geometric_splits.sh              # 15 training runs',
          'SUBMIT=1 bash scripts/run_obsnoise_geometric.sh           # parts 1+2 (10 runs)',
          'SUBMIT=1 bash scripts/run_goalmask_geometric.sh           # part 3 (2 runs)',
          'SUBMIT=1 bash scripts/slurm/submit_geometric_readouts.sh   # eval, ckpt partition',
          'python scripts/build_geometric_splits_doc.py               # this file',
          '```', '']

    out = pathlib.Path(args.out)
    out.write_text('\n'.join(L) + '\n')
    print(f'wrote {out}')


if __name__ == '__main__':
    main()
