"""Regenerate docs/reports/sac_per_split_q_2026-09-20.md from the two runs' live logs.

    python scripts/sac_split_status.py [-o docs/reports/sac_per_split_q_2026-09-20.md]

SECTION-AWARE PARSING, and that is the whole reason this is a script rather than a grep.
SB3's dump prints a bare `success_rate` key under BOTH `eval/` and `rollout/` inside one
block, so `grep success_rate` interleaves the real uniform-start evaluation with the
curriculum's training rollouts and silently reports whichever came last. The two differ by
0.2-0.3 for most of training.

EVERY PROBE APPEARS and none is marked best -- selection is never done on a held-out set.
"""
import argparse
import datetime
import json
import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
LOGS = pathlib.Path('/gscratch/robotics/harine/slurm_logs')
ARMS_ROOT = pathlib.Path('/gscratch/robotics/harine/value_arms')
# The previous render, for a what-changed diff. On /gscratch, NOT the session scratchpad:
# that is cleared between sessions and /tmp is node-local anyway, so a snapshot left there
# silently vanishes and the next diff reports the whole document as new.
SNAPSHOT = ARMS_ROOT / '.sac_doc_prev.md'

# label -> (run dir name, manifest, n_train)
RUNS = {
    'blq137': ('sac_keypoint_blq137',
               'diffusion_policy/config/splits/pusht_blockquad_bottomleft_train137.json', 137),
    'brd100': ('sac_keypoint_brd100',
               'diffusion_policy/config/splits/pusht_blockborder_train100_core50.json', 100),
}
TOTAL = 10_000_000


def latest_log(run_name):
    hits = sorted(LOGS.glob(f'va_{run_name}-*.out'), key=lambda p: p.stat().st_mtime)
    return hits[-1] if hits else None


def parse(path):
    """[{'eval/success_rate': ..., 'time/total_timesteps': ...}, ...], one per dump block.

    SB3 writes a section header as a row whose value column is empty, then the section's keys
    indented under it. Qualifying every key with its section is what keeps eval/ and rollout/
    apart.
    """
    rows, cur, sec = [], {}, None
    for line in path.read_text(errors='ignore').splitlines():
        if not line.startswith('|'):
            continue
        parts = [p.strip() for p in line.strip().strip('|').split('|')]
        if len(parts) != 2:
            continue
        key, val = parts
        if not val:
            sec = key.rstrip('/')
            continue
        cur[f'{sec}/{key}'] = val
        if key == 'total_timesteps':
            rows.append(cur)
            cur = {}
    return rows


def squeue():
    try:
        out = subprocess.run(['squeue', '-u', 'harine', '-h', '-o', '%j|%T|%M|%R|%P'],
                             capture_output=True, text=True, timeout=30).stdout
    except Exception:
        return {}
    jobs = {}
    for line in out.strip().splitlines():
        f = line.split('|')
        if len(f) == 5 and f[0].startswith('va_sac_keypoint_'):
            jobs[f[0][len('va_sac_keypoint_'):]] = {'state': f[1], 'time': f[2],
                                                    'reason': f[3], 'partition': f[4]}
    return jobs


def fnum(row, key, fmt='{:.3f}'):
    v = row.get(key)
    if v is None:
        return '--'
    try:
        return fmt.format(float(v))
    except ValueError:
        return str(v)


def build():
    jobs = squeue()
    now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
    out = [
        '# Per-split SAC keypoint Q — 2026-09-20',
        '',
        f'*Live readout, regenerated by `scripts/sac_split_status.py`. Last update {now}.*',
        '',
        '**The question.** [q_verifier_2026-09-19.md](q_verifier_2026-09-19.md) measured the SAC',
        'Q as a best-of-N verifier and found the two halves disagree: Q ranks the expert action',
        '4-9x better than `t_goal` where `t_goal` is blind, but `t_goal` wins the best-of-N sweep',
        'on all six rows. Its contamination control used `--episodes-from` on the seed-42 106',
        'manifest. That control is sound for the *ranking* half, but the best-of-N half scores on',
        'the GEOMETRIC manifests, which cut the same 206 episodes crosswise: 29 of blq137\'s 50',
        'test episodes and 24 of brd60\'s sit inside the sac106 buffer. These two runs remove that',
        'overlap structurally rather than arguing around it -- each Q is seeded only from its own',
        "manifest's train episodes, so that manifest's 50 test episodes are held out by",
        'construction.',
        '',
        '**Nothing here nominates a checkpoint.** Every probe is listed; selection is not done on',
        'a held-out set.',
        '',
        '## Runs',
        '',
        '| arm | manifest | train | state | steps | wall |',
        '|---|---|---|---|---|---|',
    ]
    parsed = {}
    for label, (run_name, manifest, n_train) in RUNS.items():
        log = latest_log(run_name)
        rows = parse(log) if log else []
        parsed[label] = rows
        j = jobs.get(label, {})
        state = j.get('state', 'not in queue')
        if state == 'PENDING':
            state = f"PENDING {j.get('reason', '')}"
        elif state == 'RUNNING':
            state = f"RUNNING {j.get('partition', '')}"
        step = rows[-1].get('time/total_timesteps', '0') if rows else '0'
        pct = f'{int(step) / TOTAL:.0%}' if str(step).isdigit() else '--'
        out.append(f'| `{run_name}` | `{pathlib.Path(manifest).name}` | {n_train} | {state} | '
                   f'{int(step):,} / {TOTAL:,} ({pct}) | {j.get("time", "--")} |')

    out += [
        '',
        'Both: `--obs keypoint --demo-episodes train`, 10M chunk steps, seed 42, otherwise the',
        "package defaults. They differ from the finished all-206 `sac_keypoint` run in exactly",
        '`split_file` and `demo_episodes`, both of which are `IDENTITY_KEYS`, so a resume cannot',
        'swap the data underneath a checkpoint.',
        '',
        '## What to read, and why',
        '',
        '| column | says |',
        '|---|---|',
        '| `eval/success_rate` | 20 episodes, **uniform start distribution, no curriculum**. Not the manifest\'s episodes -- see the caveat below. +/- 0.1 of binomial noise, so read the trend. |',
        '| `eval/max_coverage` | what `pusht_image_runner` reports, so this is the number comparable with the diffusion-policy arms. |',
        '| `rollout/success_rate` | the TRAINING envs, i.e. under the near-goal curriculum. Not the task. Listed only so the two are never confused. |',
        '| `bon/q_spread_zero_frac` | fraction of states where Q scores every candidate identically. **`t_goal`\'s own blind rate is 15-25% re-measured (28-35% originally).** This is the number the whole arm exists to beat. |',
        '| `buffer/reward_rate_tau0.95` | if this is 0, everything downstream is vacuous: a buffer of demonstrations alone carries no 0.95 terminal and the Q learns `Q = 0`. |',
        '',
        '**CAVEAT, and it is the reason `sac/eval.py policy` exists.** `eval/success_rate` above is',
        "seeded PROCEDURAL resets -- fixed in ST's *style*, not ST's *set*. The held-out number,",
        "on the manifest's own recorded episode starts, is section 'Held-out policy success'",
        'below and is filled in from `policy_eval/success_rates.jsonl` once the watcher runs.',
        '',
    ]

    for label, rows in parsed.items():
        run_name = RUNS[label][0]
        out += [f'## {run_name}', '']
        if not rows:
            out += ['No log rows yet.', '']
            continue
        keep = [r for r in rows if 'eval/success_rate' in r]
        out += ['| step | eval/succ | eval/cov | rollout/succ | q_zero_frac | q_res | rr_tau0.95 |',
                '|---:|---:|---:|---:|---:|---:|---:|']
        for r in keep:
            step = int(r.get('time/total_timesteps', 0))
            out.append(
                f"| {step:,} | {fnum(r, 'eval/success_rate', '{:.2f}')} | "
                f"{fnum(r, 'eval/max_coverage')} | {fnum(r, 'rollout/success_rate', '{:.2f}')} | "
                f"{fnum(r, 'bon/q_spread_zero_frac')} | {fnum(r, 'bon/q_resolution', '{:.4f}')} | "
                f"{fnum(r, 'buffer/reward_rate_tau0.95', '{:.4f}')} |")
        out.append('')

    # THE SHAPE OF THE CURVE, computed rather than typed, so it cannot go stale between
    # refreshes. Reporting the maximum is a fact about the measurements; it is NOT a
    # nomination -- selection is not done here and every step stays in the table above.
    def shape(rows):
        if len(rows) < 3:
            return None
        best = max(rows, key=lambda r: r['success_rate'])
        last = rows[-1]
        return (f"peak **{best['success_rate']:.2f}** ({best['n_success']}/{best['n_episodes']}) "
                f"at {best['step']:,}; latest **{last['success_rate']:.2f}** "
                f"({last['n_success']}/{last['n_episodes']}) at {last['step']:,}")

    out += ['## Held-out policy success', '',
            "The SAC actor on the MANIFEST's own 50 test episodes, via",
            '`python sac/eval.py policy <run_dir> --split test`. `sac/score.py:assert_held_out`',
            'refuses any episode inside the run\'s replay buffer, and every row records its',
            '`held_out` block, so a contaminated number can never be mistaken for a clean one.',
            '']
    rows_any = False
    tbl = ['| arm | step | success | n | max_coverage | held out |', '|---|---:|---:|---:|---:|---|']
    for label, (run_name, _, _) in RUNS.items():
        f = ARMS_ROOT / run_name / 'policy_eval' / 'success_rates.jsonl'
        if not f.is_file():
            continue
        for line in f.read_text().splitlines():
            if not line.strip():
                continue
            r = json.loads(line)
            rows_any = True
            tbl.append(f"| `{run_name}` | {r['step']:,} | {r['success_rate']:.3f} | "
                       f"{r['n_success']}/{r['n_episodes']} | {r['max_coverage']:.3f} | "
                       f"{r['held_out']['held_out']} |")
    # the comparison that motivates the whole section
    gaps = []
    for label, (run_name, _, _) in RUNS.items():
        f = ARMS_ROOT / run_name / 'policy_eval' / 'success_rates.jsonl'
        if not f.is_file():
            continue
        hr = sorted((json.loads(l) for l in f.read_text().splitlines() if l.strip()),
                    key=lambda r: r['step'])
        sh = shape(hr)
        if not sh:
            continue
        # A WINDOW OF PROBES, NOT THE NEAREST ONE. The procedural eval is 20 episodes and
        # swings 0.55-0.75 between consecutive probes, so "held-out 0.56 vs procedural 0.70"
        # picked out of one pair is mostly which probe you landed on -- the neighbouring probe
        # reads 0.55 and inverts the claim. Comparing means over the same step window is what
        # the numbers actually support, and the spread is reported so the reader can see the
        # procedural series is the noisy one (sd ~3x the held-out series).
        proc = [r for r in parsed.get(label, []) if 'eval/success_rate' in r]
        lo = hr[len(hr) // 2]['step']                 # the later half, past the early transient
        pv = [float(r['eval/success_rate']) for r in proc
              if int(r.get('time/total_timesteps', 0)) >= lo]
        hv = [r['success_rate'] for r in hr if r['step'] >= lo]
        line = f'- **{run_name}**: {sh}.'
        if len(pv) >= 5 and len(hv) >= 5:
            import statistics
            pm, hm = statistics.mean(pv), statistics.mean(hv)
            line += (f" Over steps >= {lo:,}: procedural `eval/success_rate` averages "
                     f"**{pm:.3f}** (n={len(pv)}, sd {statistics.pstdev(pv):.3f}, 20 episodes "
                     f"each) against **{hm:.3f}** held out (n={len(hv)}, sd "
                     f"{statistics.pstdev(hv):.3f}, 50 episodes each)")
            if pm - hm >= 0.05:
                # THIS ARM'S manifest, not SAC in general. brd100 runs this same comparison at
                # -0.04 on the same code and budget, so a gap here is a property of which
                # episodes the manifest holds out -- blq137 holds out bottomleft-quadrant T
                # starts -- and not something the algorithm does everywhere. Saying otherwise
                # would generalise from one arm to a claim the two jointly contradict.
                line += (f' -- a gap of {pm - hm:+.3f}, so on THIS manifest the procedural '
                         'number flatters the arm and the held-out one is what should be '
                         'quoted. Whether other manifests show a gap is per-arm: see the '
                         'other rows.')
            elif hm - pm >= 0.05:
                # THE OTHER DIRECTION, and it needs saying rather than being folded into "no
                # gap": brd100's held-out episodes score ABOVE its procedural ones. A branch
                # that only tested the blq137 direction printed "not yet a gap" over a real
                # 0.05 separation, which reads as agreement between the two numbers when they
                # disagree. Its test set is the blockborder INTERIOR 50, further from every
                # wall than a uniform draw, so easier is the expected sign here.
                line += (f' -- held out is HIGHER by {hm - pm:.3f}. This manifest holds out the '
                         'interior-core episodes, which are further from the arena walls than '
                         'a uniform procedural draw, so the held-out set being the easier one '
                         'is the expected direction for this split, not an anomaly.')
            elif max(r['success_rate'] for r in hr) == 0.0:
                line += ', i.e. neither has left the floor yet; too early to compare.'
            else:
                line += (f' -- a difference of {pm - hm:+.3f}, too small to call either way '
                         'against the procedural series\' own spread.')
        gaps.append(line)
    if gaps:
        out += gaps + ['']

    out += (tbl + [''] if rows_any else
            ['*Not measured yet -- the watcher runs once checkpoints are worth scoring.*', '',
             'Reference, and **not** a held-out number: the all-206 `sac_keypoint` arm at 10M',
             "scores **0.740 (37/50)**, max coverage 0.811, on brd100's 50 test episodes -- but",
             'all 50 are in its buffer (`held_out: false`, `n_overlap: 50`). That is the',
             'contaminated ceiling these runs are read against, not a result.', ''])

    out += ['## Next', '',
            'The Q evaluation is deferred until the policies are worth verifying. When it runs it',
            'follows `sac/README.md` > *The Q evaluation procedure*, driven by',
            '`scripts/slurm/q_eval_arms.sh`: 11 rows, `--split test`, with the brd60 checkpoints',
            'scored under the brd100 Q because the two share a test set exactly and brd60\'s train',
            'is a strict subset of brd100\'s.', '']
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('-o', '--out', default='docs/reports/sac_per_split_q_2026-09-20.md')
    ap.add_argument('--diff', action='store_true',
                    help='print what changed since the last render, then update it')
    a = ap.parse_args()
    p = ROOT / a.out
    p.parent.mkdir(parents=True, exist_ok=True)
    text = build()
    if a.diff and SNAPSHOT.is_file():
        strip = lambda t: [l for l in t.splitlines() if 'Last update' not in l]  # noqa: E731
        import difflib
        d = list(difflib.unified_diff(strip(SNAPSHOT.read_text()), strip(text),
                                      'previous', 'current', lineterm='', n=0))
        print('\n'.join(d) if d else '(no change since the last render)')
    p.write_text(text)
    SNAPSHOT.write_text(text)
    print(f'wrote {p}')


if __name__ == '__main__':
    main()
