"""Regenerate the checkpoint x selection x n grid section of LATEST_SUCCESS_RATES.md.

Idempotent: rewrites everything between the marker comments, appending the block if it
is not there yet. Safe to run against an in-progress sweep -- only completed cells appear.

    python scripts/update_latest_with_grid.py
"""
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOC = ROOT / 'LATEST_SUCCESS_RATES.md'
LOG = ROOT / 'logs' / 'bon_grid_30demo.log'
LOG_N64_P1 = ROOT / 'logs' / 'bon_grid_30demo_n64.log.part1'  # pre-timeout-fix run
LOG_N64 = ROOT / 'logs' / 'bon_grid_30demo_n64.log'   # the n in {32,64} argmax slice
LOG_UNET = ROOT / 'logs' / 'run_unetbc_30demo.log'    # UNet BC train + eval
LOG_BIG = ROOT / 'logs' / 'run_st_big_30demo.log'     # ST at 6x8x1024, k=1 and k=16
START = '<!-- BEGIN grid (generated by scripts/update_latest_with_grid.py) -->'
END = '<!-- END grid -->'


def render(metric, split):
    r = subprocess.run(
        [sys.executable, str(ROOT / 'scripts/bon_grid_table.py'),
         '--log', str(LOG), '--log', str(LOG_N64), '--log', str(LOG_N64_P1),
         '--log', str(LOG_UNET), '--log', str(LOG_BIG),
         '--metric', metric, '--split', split],
        capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else ''


def main():
    if not LOG.exists():
        sys.exit(f'no grid log at {LOG}')
    done = len(re.findall(r'^=== \S+ \w+ step_\d+ \w+ ===', LOG.read_text(), re.M))
    finished = 'grid done' in LOG.read_text()

    parts = [START, '', '## 2. Best-of-n grid -- policy x checkpoint x selection', '']
    parts.append(
        f'Every `step_*.ckpt` on the 10k grid x {{argmax, softmax, final_pass}} x '
        f'n in {{1,2,4,8,16}}, both arms. **{done}/60 combos complete'
        + ('' if finished else ' -- sweep still running, table is partial') + '.**\n')
    parts.append(
        'Pick a checkpoint on **val** and read **test** at the same row; this grid exists '
        'so a checkpoint never has to be pre-selected. Selecting by maximising test '
        'inflates the reported number by 1-2 SE.\n')
    parts.append(
        '**n counts GENERATIONS, identically under all three rules**, so the columns are '
        'matched on compute. At n=1 there is nothing to select, so all three rules run the '
        'same empty-context conditional and their n=1 cells must agree exactly -- a '
        'disagreement there is a bug, not a result.\n')
    parts.append(
        'A policy label carries its TRAINED width as `k` (`max_actions`, matching the '
        'run dirs); the columns are the EVAL width `n`. `ST-diffusion-k1` read at n=16 is '
        'sampled 16 times i.i.d., since at its trained width of 1 there is no context to '
        'condition on.\n')
    parts.append(
        '**ST-diffusion-k1 has no search context at all** -- `max_context_actions` is 0 and its '
        '`cond_pos_emb` is None, so the model discards any context handed to it '
        '(verified: contexts differing by 200x give bit-identical actions). Its n '
        'candidates are therefore n INDEPENDENT draws, which is what makes it a clean '
        'test-time-search baseline. One consequence: **ST-k1/final_pass is not a selection '
        'rule** -- with nothing to condition on, the returned sample is drawn from the '
        'same distribution as any other, so that row measures a single plain k1 draw at '
        'n times the cost, and is flat in n rather than rising. Do not read it as a '
        'comparison against k1/argmax.\n')
    # bon_grid_table.py emits its own "### SPLIT -- metric" heading per table
    for split in ('test', 'val'):
        for metric in ('reward', 'success'):
            body = render(metric, split)
            if body:
                parts += [body, '']
    parts += ['Regenerate: `python scripts/update_latest_with_grid.py`', '', END]
    block = '\n'.join(parts)

    doc = DOC.read_text()
    if START in doc and END in doc:
        doc = re.sub(re.escape(START) + r'.*?' + re.escape(END), block, doc, flags=re.S)
    else:
        doc = doc.rstrip() + '\n\n' + block + '\n'
    DOC.write_text(doc)
    print(f'updated {DOC.name}: {done}/60 combos'
          + (' (sweep finished)' if finished else ' (in progress)'))


if __name__ == '__main__':
    main()
