"""Regenerate the checkpoint x selection x n grid section of LATEST_SUCCESS_RATES.md.

Idempotent: rewrites everything between the marker comments, appending the block if it
is not there yet. Safe to run against an in-progress sweep -- only completed cells appear.

    python scripts/update_latest_with_grid.py
"""
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOC = ROOT / 'LATEST_SUCCESS_RATES.md'
LOG = ROOT / 'logs' / 'bon_grid_30demo.log'
START = '<!-- BEGIN grid (generated by scripts/update_latest_with_grid.py) -->'
END = '<!-- END grid -->'


def render(metric, split):
    r = subprocess.run(
        [sys.executable, str(ROOT / 'scripts/bon_grid_table.py'),
         '--log', str(LOG), '--metric', metric, '--split', split],
        capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else ''


def main():
    if not LOG.exists():
        sys.exit(f'no grid log at {LOG}')
    done = len(re.findall(r'^=== \S+ \w+ step_\d+ \w+ ===', LOG.read_text(), re.M))
    finished = 'grid done' in LOG.read_text()

    parts = [START, '', '## 6. Full checkpoint x selection x n grid', '']
    parts.append(
        f'Every `step_*.ckpt` on the 10k grid x {{argmax, softmax, final_pass}} x '
        f'n in {{1,2,4,8,16}}, both arms. **{done}/60 combos complete'
        + ('' if finished else ' -- sweep still running, table is partial') + '.**\n')
    parts.append(
        'This exists so a checkpoint never has to be pre-selected: pick on **val** and '
        'read **test** at the same row. Selecting by maximising test (which is how the '
        'section 2 checkpoints were chosen) inflates the reported number by 1-2 SE.\n')
    parts.append(
        '**n counts GENERATIONS, identically under all three rules**, so the columns are '
        'matched on compute. At n=1 there is nothing to select, so all three rules run '
        'the same empty-context conditional and the n=1 rows must agree exactly -- a '
        'disagreement there is a bug, not a result. (Grids generated before 2026-08-18 '
        'do not have this property: `final_pass` cost n+1 generations, and softmax drew '
        'from the sampler\'s RNG stream, so its n=1 column was a reseeded replicate '
        'rather than the same rollout.)\n')
    # bon_grid_table.py emits its own "### ARM -- split metric" headings, so none here
    for split in ('test', 'val'):
        for metric in ('reward', 'success'):
            body = render(metric, split)
            if body:
                parts += [body, '']
    parts += ['Regenerate: `python scripts/update_latest_with_grid.py`', '', END]
    block = '\n'.join(parts)

    doc = DOC.read_text()
    if START in doc and END in doc:
        doc = re.sub(re.escape(START) + r'.*?' + re.escape(END), block, doc, flags=re.S)
    else:
        doc = doc.rstrip() + '\n\n' + block + '\n'
    DOC.write_text(doc)
    print(f'updated {DOC.name}: {done}/60 combos'
          + (' (sweep finished)' if finished else ' (in progress)'))


if __name__ == '__main__':
    main()
